/* 
 * V1__createTaskTable.sql
 * Creates all database artifacts required by the tasks module of the JEETRAIN application
 */
/*
 * Table containing all tasks managed by the UTRAIN application
 */
CREATE TABLE T_TASK (
	TASK_ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SUBJECT VARCHAR(80) NOT NULL ,
    DESCRIPTION VARCHAR(1024) NOT NULL ,
    CATEGORY INT NOT NULL ,
    PRIORITY INT NOT NULL ,
    LIFECYCLE_STATE INT NOT NULL ,
    SUBMISSION_DATE TIMESTAMP, 
    SUBMITTER_ID VARCHAR(16),
    DUE_DATE TIMESTAMP ,
    COMPLETION_RATE INT NOT NULL ,
    COMPLETION_DATE TIMESTAMP ,
    COMPLETER_ID VARCHAR(16) ,
    RESPONSIBLE_ID VARCHAR(16) ,
    AFFECTED_PROJECT_ID VARCHAR(16),
    AFFECTED_APPLICATION_ID VARCHAR(8),
    AFFECTED_MODULE VARCHAR(32),
    AFFECTED_RESOURCE VARCHAR(256),
    ESTIMATED_EFFORT INT,
    EXPECTED_EFFORT INT,
    ACTUAL_EFFORT INT,
    VERSION INT NOT NULL,
    CREATOR_ID VARCHAR(16) NOT NULL ,
    CREATION_DATE TIMESTAMP NOT NULL ,
    LAST_MODIFIER_ID VARCHAR(16) NOT NULL,
    LAST_MODIFICATION_DATE TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX X_TASK
	ON T_TASK
   (TASK_ID ASC);
