/* 
 * V3__createUserModel.sql
 * Erzeugt alle Datenbank-Objekte für das User-Datenmodell.
 */

/*
 * Enthält alle registrierten Benutzer der JEETRAIN Applikation
 */
CREATE TABLE T_USER (
	USER_ID VARCHAR(16) PRIMARY KEY NOT NULL ,
    PASSWORD VARCHAR(64) NOT NULL ,
    FIRST_NAME VARCHAR(64) NOT NULL ,
    LAST_NAME VARCHAR(64) NOT NULL ,
    FULL_NAME VARCHAR(128) NOT NULL ,
    GENDER INT NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL ,
    EMAIL VARCHAR(64) NOT NULL ,
    PHONE VARCHAR(16) ,
    MOBILE VARCHAR(16) ,
    VERSION INT NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFICATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX X_USER
	ON T_USER
   (USER_ID ASC);
   
/*
 * Enthält die Rollenzuweisungen aller JEETRAIN Benutzer
 */
CREATE TABLE T_ROLE(
	ROLE_ID BIGINT PRIMARY KEY NOT NULL ,
	USER_ID VARCHAR(16) ,
    ROLE_NAME VARCHAR(32) NOT NULL ,
    LAST_MODIFICATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX X_ROLE
   ON T_ROLE
   (ROLE_ID);

CREATE INDEX X_ROLE_BY_USER_ID
   ON T_ROLE
   (USER_ID ASC);

