/* 
 * V4__createUserPreferencesModel.sql
 * Adds all DB artifacts of the user preferences model.
 */

/*
 * key-value-store like table with all preferences of an registered user
 */
CREATE TABLE T_PREFERENCE (
	PREFERENCE_ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT ,
	USER_ID VARCHAR(16) NOT NULL ,
    NAME VARCHAR(32) NOT NULL ,
    VALUE VARCHAR(256) ,
    VERSION INT NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFICATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX X_PREFERENCE_ID
	ON T_PREFERENCE
   (PREFERENCE_ID ASC);

CREATE UNIQUE INDEX X_PREFERENCE_NATURAL_ID
	ON T_PREFERENCE
   (USER_ID, NAME ASC);

